# Generated by Django 4.2.3 on 2024-11-29 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilograms"),
                            ("g", "Grams"),
                            ("l", "Liters"),
                            ("ml", "Milliliters"),
                            ("pcs", "Pieces"),
                        ],
                        default="pcs",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("produce", "Produce"),
                            ("meat", "Meat"),
                            ("dairy", "Dairy"),
                            ("dry_goods", "Dry Goods"),
                            ("spices", "Spices"),
                            ("beverages", "Beverages"),
                        ],
                        default="dry_goods",
                        max_length=20,
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=2, default=10, max_digits=10),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                ("last_restocked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_perishable", models.BooleanField(default=False)),
                ("expiration_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "ingredients",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="menu_items/"),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_vegetarian", models.BooleanField(default=False)),
                (
                    "preparation_time",
                    models.IntegerField(help_text="Preparation time in minutes"),
                ),
            ],
            options={
                "db_table": "kitchen_menu_items",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "kitchen_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("item_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kitchen_order_items",
                        to="kitchen.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_order_items",
                        to="kitchen.order",
                    ),
                ),
            ],
            options={
                "db_table": "kitchen_order_items",
            },
        ),
        migrations.CreateModel(
            name="MenuItemIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kitchen.ingredient",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kitchen.menuitem",
                    ),
                ),
            ],
            options={
                "db_table": "menu_item_ingredients",
                "unique_together": {("menu_item", "ingredient")},
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("usage", "Usage"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="kitchen.ingredient",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_transactions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="ingredient",
            name="menu_items",
            field=models.ManyToManyField(
                through="kitchen.MenuItemIngredient", to="kitchen.menuitem"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=models.Index(
                fields=["name", "category"], name="ingredients_name_267140_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=models.Index(
                fields=["quantity", "reorder_level"],
                name="ingredients_quantit_b7817a_idx",
            ),
        ),
    ]
