# Generated by Django 4.2.3 on 2024-11-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItemProxy",
            fields=[
                (
                    "menu_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="menu_proxy",
                        serialize=False,
                        to="kitchen.menuitem",
                    ),
                ),
                ("display_priority", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Menu Item Proxy",
                "verbose_name_plural": "Menu Item Proxies",
                "db_table": "menu_item_proxies",
            },
        ),
    ]
